// <auto-generated />
using EmailSender.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmailSender1.Migrations
{
    [DbContext(typeof(EmailReciverDbContext))]
    [Migration("20240219165210_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmailSender.Models.Entities.AdressBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("adresses");
                });

            modelBuilder.Entity("EmailSender.Models.Entities.EmailReciver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdressesBookId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surename")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdressesBookId");

                    b.ToTable("emailRecivers");
                });

            modelBuilder.Entity("EmailSender.Models.Entities.EmailReciver", b =>
                {
                    b.HasOne("EmailSender.Models.Entities.AdressBook", "AdressesBook")
                        .WithMany("EmailRecivers")
                        .HasForeignKey("AdressesBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EmailSender.Models.Entities.CsvInformations", "csvInformations", b1 =>
                        {
                            b1.Property<int>("EmailReciverId")
                                .HasColumnType("int");

                            b1.Property<string>("Property1")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Property2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Property3")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Property4")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Property5")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmailReciverId");

                            b1.ToTable("emailRecivers");

                            b1.WithOwner()
                                .HasForeignKey("EmailReciverId");
                        });

                    b.Navigation("AdressesBook");

                    b.Navigation("csvInformations");
                });

            modelBuilder.Entity("EmailSender.Models.Entities.AdressBook", b =>
                {
                    b.Navigation("EmailRecivers");
                });
#pragma warning restore 612, 618
        }
    }
}
